### ISSUE TITLE
Failed To Create Texture

### ISSUE THREAD

**Issue by joaovitorzktz** [LagradOst/BlueFireColorbotPublic#1]
I Open The Hack But Give Me This Error
![image](https://user-images.githubusercontent.com/71929968/111917382-e899da80-8a3c-11eb-80d2-efc90cab3677.png)

**Comment by LagradOst** [comment]
1. The game must be in view
2. The game must not be in fullscreen
3. idk some ppl have problems with it

**Comment by joaovitorzktz** [comment]
thx its working now :)
